openapi: 3.0.3
info:
  title: Swagger EKAN API de beneficiarios
  description: API para EKAN
  termsOfService: http://swagger.io/terms/
  contact:
    email: cristfp@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: https://github.com/cristfp/ekan/tree/master
servers:
  - url: https://github.com/cristfp/ekan/tree/master
tags:
  - name: beneficiarios
    description: API de beneficiarios
    externalDocs:
      description: Find out more
      url: http://swagger.io
  
paths:
  /beneficiarios:
    get:
      tags:
        - beneficiarios
      summary: Returna  todos beneficiarios
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
      security:
        - api_key: []
    put:
      tags:
        - beneficiarios
      summary: atualiza um beneficiario
      description: atualiza um beneficiario
      operationId: updateBeneficiarios
          
          
      responses:
        '200':
          description: Successful operation
          
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
    post:
      tags:
        - beneficiarios
      summary: Adiciona um novo beneficiario
      description: Adiciona um novo beneficiario
      operationId: addBeneficiarios
      requestBody:
        description: Adiciona um novo beneficiario
        content:
          application/json:
            schema:
              $ref: ''
          application/xml:
            schema:
              $ref: ''
          application/x-www-form-urlencoded:
            schema:
              $ref: ''
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: ''          
            application/xml:
              schema:
                $ref: ''
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:beneficiarios
            - read:beneficiarios
  
  /beneficiarios/{Id}:
    post:
      tags:
        - beneficiarios
      summary: atualiza os beneficiarios
      description: ''
      operationId: atualiza os beneficiarios
      parameters:
        - name: Id
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
       
      responses:
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:pets
            - read:pets
    delete:
      tags:
        - beneficiarios
      summary: Deleta um beneficiario
      description: Deleta um beneficiario
      operationId: deleteBeneficiario
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: Id
          in: path
          description: Beneficiario id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid beneficiario value
      security:
        - petstore_auth:
            - write:beneficiarios
            - read:beneficiarios
  
  